### ISSUE TITLE
Adding "Thorsten - Open German Voice Dataset" to the list

### ISSUE THREAD

**Issue by thorstenMueller** [adbar/German-NLP#17]
I’d like to send a PR for adding my „Thorsten - Open German Voice Dataset“ (https://github.com/thorstenMueller/deep-learning-german-tts/) to that great list. It contains two voice datasets (_neutral and emotional_) with over 23 hours of pure german audio by a single speaker.

Is „Speech NLP“ right chapter or where could i add it?

**Comment by adbar** [comment]
Hi @thorstenMueller, that's correct, thanks in advance!

The title "Speech NLP" isn't great and the section could be improved. Feel free to helping expanding the list if you know useful off-the-shelf resources.
